#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import listdir, path
from sys import argv, stderr

action = argv[1]
assert(action in ['find-media', 'search'])

import config

from helpers import tar

if action == 'find-media':
    for source_name in config.sources.keys():
        source = config.sources[source_name]
        if source_name == 'pubmed':
            metadata_raw_source_path = config.get_metadata_raw_source_path(source_name)
            listing = listdir(metadata_raw_source_path)
            for filename in listing:
                tar.find_media(
                    path.join(metadata_raw_source_path, filename),
                    config.get_metadata_refined_source_path(source_name)
                )

if action == 'search':
    raise NotImplementedError
