#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path
from sys import argv, stderr

action = argv[1]
target = ' '.join(argv[2:])

try:
    assert(action in ['download-metadata', 'download-media'])
except AssertionError:
    stderr.write("""
oa-get – Open Access Importer download operations

usage:  oa-get download-metadata [source] |
        oa-get download-media [source]

""")

import config

from helpers import ftp

if action == 'metadata':
    for source_name in config.sources.keys():
        source = config.sources[source_name]
        if source['type'] == 'ftp':
            ftp.get(source['server'], source['files'],
                config.get_metadata_raw_source_path(source_name))

if action == 'media':
    raise NotImplementedError
