#!/bin/sh

# clear database to get rid of old data
./oa-cache clear-database pmc_doi

# normal workflow for OAMI
./oa-get download-metadata pmc_doi
./oa-cache find-media pmc_doi
./oa-get download-media pmc_doi
./oa-cache convert-media pmc_doi
./oa-put upload-media pmc_doi
